### ISSUE TITLE
[feature request] 'new episodes' view across podcasts?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [gilcu3/hullcaster#3] opened 2024-07-23 08:39 UTC
hi there,
thanks for working on hullcaster. :)
i've been enjoying using the application, but after importing some more podcasts to it, found myself a bit overwhelmed looking for new episodes: while i'd have many podcasts, i wouldn't be sure which ones have new episodes.
would you consider perhaps having a view that lists episodes by recency across different podcasts?

**Comment by gilcu3** [comment] 2024-07-23 09:22
Indeed, that's something that should certainly be added. I have most trouble figuring out where to put the UI for it. Do you have any idea in mind?

**Comment by KiaraGrouwstra** [comment] 2024-07-23 10:29
i suppose in such a view the present Details and Queue panes would remain relevant, whereas i imagine this view to kind of serve as an alternative to the present Episodes pane.
perhaps we could say have a keyboard shortcut toggling between episodes vs this view for the left pane then?

**Comment by gilcu3** [comment] 2024-07-23 12:25
There used to be something like that in the original `shellcaster`, although it would just filter the view and leave element with unread items only. What you propose seems better. A global key (`u` from unread) would change the left panel from Podcasts/Episodes to a list of unread Episodes ordered by date. I will give it a try and get back here for feedback.

**Comment by gilcu3** [comment] 2024-08-06 15:29
@KiaraGrouwstra I just pushed initial support for this feature in 00e117827b842afb1514d6d10daca5cc075c49d8. It should work when the podcast list is active and `u` is pressed by default. Could you test it (current `develop` branch) and let me know if you find bugs or unexpected behaviors?

**Comment by gilcu3** [comment] 2024-08-06 17:31
Thanks for the comments, I will try to reply one by one.

- I will add it to the bottom bar in the next commit.
- I will need to check that, you mean that it occupies less space? That must be a bug.
- Adding the title would take too much space. What I was figuring at some point was to add it to the details view, now it seems necessary. I will add it in the next commit as well.
- They are sorted by recency (specifically publication date, might differ from availability date which is not stored anywhere), most recent first. If you find that's not the case show me an example, because that would need fixing.

**Comment by KiaraGrouwstra** [comment] 2024-08-06 18:09
hm, looks like my podcasts may still be syncing, i'll check back on publication date, might be ok.

here's a screenshot demonstrating the new view taking up less space for me than its parent view:

![image](https://github.com/user-attachments/assets/e5f82ac8-9daa-410f-87a3-500cb84eeb27)

**Comment by gilcu3** [comment] 2024-08-06 20:16
I was able to reproduce that bug only after resizing the window. 

Everything should be fixed in the current HEAD 8486700 of the develop branch. Let me know if I missed anything.

**Comment by KiaraGrouwstra** [comment] 2024-08-07 20:23
nice! this def addresses it, i'd gladly see this merged. 😍

**Comment by KiaraGrouwstra** [comment] 2024-08-07 20:38
as a nitpick, i'm finding myself manually marking played episodes as marked, i.e. for every episode in the list i would invoke both `e` to enqueue and `m` to remove them from the list of new episodes. UX-wise i wouldn't mind if enqueuing perhaps would marked as played as well, tho i'm not sure if everyone would feel that way.
kinda minor gripe tho either way.

**Comment by gilcu3** [comment] 2024-08-07 22:17
At least on my own use case that would not totally work, as I use the sync feature with `AntennaPod` on Android and therefore only want to mark something as read when it is actually read. 

Syncing the queue is a long term issue with the gpodder API, that should be solved once the new OpenPodcasts API becomes stable.

There is an option to mark an episode as read when it is played, maybe enabling that might feat your use case a bit better?

**Comment by KiaraGrouwstra** [comment] 2024-08-08 16:19
oo nice. i've been using antennapod myself as well, so i should prob try that out too. :smile_cat:

the manual mark as read is fine, yeah. feel free to close this. :)

**Closed** 2024-08-08 16:22 UTC

**Comment by gilcu3** [comment] 2024-08-22 07:33
@KiaraGrouwstra you were right, today I hit the sort by recency bug, it would happen when only adding a new podcast with older episodes. Should be fixed in be5964c!
